name: Build Docker Image
on:
  push:
    branches:
      - '**'      # Trigger on push
    tags-ignore:
      - '*.*'     # Ignore release events
    paths-ignore:
      - README.md # Ignore changes to readme

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build Docker image
      run: docker build . -f Dockerfile
